---
controller_dependency_check: false
usecases:
  - name: rhel
    url: https://github.com/ansible-collections/community.rhel_ops
    version: main
  - name: network
    url: https://github.com/redhat-cop/network.backup
    version: main
  - name: windows
    url: https://github.com/redhat-cop/infra.windows_ops
    version: main
  - name: cloud
    url: https://github.com/redhat-cop/cloud.aws_ops
    version: main
